SHMUDataset:
  # Absolute path to the list containing dates used for training, validation and testing
  # The path can contain {split} that is replaced with train/test/valid
  metadata: "/scratch/p709-24-2/Delft/scratch/ppavlik/metadata_fix_with_eth.csv"
  # path and filename can contain the following tokens:
  # {year:*}, {month:*}, {day:*}, {hour:*}, {minute:*}, {second:*}
  # Path to archive
  path: "/scratch/p709-24-2/Delft/scratch/ppavlik/PCP_cleaned"
  path_eth: "/scratch/p709-24-2/Delft/scratch/ppavlik/ETH"
  # Number of frames used as input
  input_block_length: 4
  # Number of frames that are predicted
  prediction_block_length: 18
  # Bounding box used as Python indices
  # written as [x1, x2, y1, x2] that corresponds to image[x1:x2, y1:y2]
  bbox: [215,-214,214,-214]
  # Original Image size
  image_size: [336, 272]
  transform_to_mmh: true
  normalization_method: "none"
augmentations:
  horizontal_flip: true
  vertical_flip: true
